### PR TITLE
updated adding a pet

### PR DESCRIPTION
**Pull request by AdamIverson**
hii

### CODE REVIEW

**Review by AdamIverson — COMMENTED** [review]
great

**Review by AdamIverson — COMMENTED** [review]
great

**Review by Zane-Klausing — APPROVED** [review]
approved!

**Review by Zane-Klausing — APPROVED** [review]
approved!

**Review by Zane-Klausing — COMMENTED** [review]
approved!

**Review by Zane-Klausing — APPROVED** [review]
approved!

**Review by Zane-Klausing — APPROVED** [review]
approved!

**Review by Zane-Klausing — APPROVED** [review]
approved!

**Pull request merged**
